version: '3.9'
services:
  db1:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'customerdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'kishore'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'mysql'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
      #volumes:
      #- my-db:/var/lib/mysql
# Names our volume
#volumes:
  db2:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'itemdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'kishore'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'mysql'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
      #volumes:
      #- my-db:/var/lib/mysql
  # Names our volume
  #volumes: